---
name: Docs

on:
  push:
    branches:
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: Run Yard Doc
      run: |
        gem install yard
        yard doc
    - name: Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
          branch: gh-pages
          folder: doc/
